a. details about repo;
practical tasks from “computer systems design theory”

b. task details;
∙ Hardware (HW)
∙ Desktop software (SW)
∙ Web software (WEB)
∙ Mobile software (APP)
The simple games will be used as projects for development. But students can propose
their own project that will be used as their diploma work. Such a project must be
confirmed by their mentor.

c. student number;
Student number HW i-face   Game Data    driven format
       #5         SPI        tetris         JSON
